### ISSUE TITLE
ValueError: location_losses, cls_losses and decoded_boxlist_list do not have compatible shapes.

### ISSUE THREAD

**Issue by linchaozhang** [generalized-iou/g-tensorflow-models#1]
```
Traceback (most recent call last):
  File "object_detection/model_main.py", line 111, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 107, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 451, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 590, in run
    return self.run_local()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/training.py", line 691, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1170, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/media/data2/zlc/Network_tensorflow/models/research/object_detection/model_lib.py", line 322, in model_fn
    prediction_dict, features[fields.InputDataFields.true_image_shape])
  File "/media/data2/zlc/Network_tensorflow/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 836, in loss
    location_losses, cls_losses, prediction_dict, match_list)
  File "/media/data2/zlc/Network_tensorflow/models/research/object_detection/meta_architectures/ssd_meta_arch.py", line 1069, in _apply_hard_mining
    match_list=match_list)
  File "/media/data2/zlc/Network_tensorflow/models/research/object_detection/core/losses.py", line 577, in __call__
    raise ValueError('location_losses, cls_losses and decoded_boxlist_list '
ValueError: location_losses, cls_losses and decoded_boxlist_list do not have compatible shapes.
```
i meet the same question when using weight_iou.

**Comment by nathantsoi** [comment]
could you post exactly how you ran this and i can try to help debug. seems like `location_losses`, `cls_losses` and `decoded_boxlist_list` do not have the same number of images?

**Comment by BeautyMess** [comment]
@nathantsoi meet the same question.

in the .config file:
```
model {
  ssd {
    num_classes: 90
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
    anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }
    }
    box_predictor {
      convolutional_box_predictor {
        min_depth: 0
        max_depth: 0
        num_layers_before_predictor: 0
        use_dropout: false
        dropout_keep_probability: 0.8
        kernel_size: 1
        box_code_size: 4
        apply_sigmoid_to_scores: false
        conv_hyperparams {
          activation: RELU_6,
          regularizer {
            l2_regularizer {
              weight: 0.00004
            }
          }
          initializer {
            truncated_normal_initializer {
              stddev: 0.03
              mean: 0.0
            }
          }
          batch_norm {
            train: true,
            scale: true,
            center: true,
            decay: 0.9997,
            epsilon: 0.001,
          }
        }
      }
    }
    feature_extractor {
      type: 'ssd_mobilenet_v2'
      min_depth: 16
      depth_multiplier: 1.0
      conv_hyperparams {
        activation: RELU_6,
        regularizer {
          l2_regularizer {
            weight: 0.00004
          }
        }
        initializer {
          truncated_normal_initializer {
            stddev: 0.03
            mean: 0.0
          }
        }
        batch_norm {
          train: true,
          scale: true,
          center: true,
          decay: 0.9997,
          epsilon: 0.001,
        }
      }
    }
    loss {
      classification_loss {
        weighted_sigmoid {
        }
      }
      localization_loss {
        weighted_giou {
        }
      }
      hard_example_miner {
        num_hard_examples: 3000
        iou_threshold: 0.99
        loss_type: CLASSIFICATION
        max_negatives_per_positive: 3
        min_negatives_per_image: 3
      }
      classification_weight: 1.0
      localization_weight: 1.0
    }
    normalize_loss_by_num_matches: true
    post_processing {
      batch_non_max_suppression {
        score_threshold: 1e-8
        iou_threshold: 0.6
        max_detections_per_class: 100
        max_total_detections: 100
      }
      score_converter: SIGMOID
    }
  }
}
```

In the  localization_loss field, meet the problem when using **weighted_giou** or **weighted_iou**.
The reason I guess is that I try to finetune from a pre-trained ssd model which uses a weighted_smooth_l1 loss as its localization loss. And that causes an incompatible shape error. But I am not sure of it.

And I feel confused whether we need to set the localization loss as weighted_giou to make the giou work or we just run the training the same as what we did before. If weighted_giou needs to be set, does it mean that we should train it from scratch instead of just finetuning from some pre-trained models.

That's my confusion. And thanks for your great work about GIoU and the reply.
